Update to 0.1.3
-   Change .picardmetricsrc to picardmetrics.conf

-   Delete newly created BAM file after metrics have been computed.

-   Add install_deps script to simplify installing dependencies

-   Use hg38 in make_rRNA_intervals and make_refFlat

diff --git a/picardmetrics b/picardmetrics
--- a/picardmetrics
+++ b/picardmetrics
@@ -12,7 +12,7 @@ main() {
     shift
     main_run $@
   else
-    echo "picardmetrics v0.1.2 - 2015-04-09"
+    echo "picardmetrics v0.1.3 - 2015-04-23"
     echo "Usage: picardmetrics COMMAND"
     echo "  run         Run the Picard tools on a given BAM file."
     echo "  collate     Collate metrics files for multiple BAM files."
@@ -23,14 +23,14 @@ main_run() {
   # Ensure that the script was called with correct arguments.
   if [[ "$1" == "" ]]; then
     echo "Usage: picardmetrics run [-f FILE] [-o DIR] [-r] <file.bam>"
-    echo "  -f FILE     The configuration file. (Default: .picardmetricsrc)"
+    echo "  -f FILE     The configuration file. (Default: picardmetrics.conf)"
     echo "  -o DIR      Write output files in this directory. (Default: .)"
     echo "  -r          The BAM file has RNA-seq reads. (Default: false)"
     return 0
   fi
 
   # By default, look for the config file in the user's home directory.
-  PICARDMETRICS_CONFIG=~/.picardmetricsrc
+  PICARDMETRICS_CONFIG=~/picardmetrics.conf
 
   # By default, write output to the user's current working directory.
   OUT_DIR="."
@@ -93,7 +93,7 @@ main_run() {
 
   local sorted=$(basename $bam)
 
-  # Sort the BAM file if it is not already sorted.
+  # Create a sorted BAM file if the given file is not sorted.
   if ! bam_sorted "$bam"; then
     # Picard tools require a coordinate-sorted BAM file.
     if [[ ! -s "$sorted" || "$bam" -nt "$sorted" ]] \
@@ -101,7 +101,7 @@ main_run() {
       sort_sam "$bam" "$sorted"
     fi
   else
-    # The BAM file is already sorted, so make a symlink to it.
+    # Make a symlink if the given BAM file is already sorted.
     if ! ln -sf "$bam" "$sorted"; then
       echo "ERROR: Cannot symlink '$bam' to '$sorted'" >&2
       exit 1
@@ -110,6 +110,11 @@ main_run() {
 
   # Run all of the Picard tools.
   compute_metrics "$sorted" "$RNASEQ"
+
+  # Delete the extra BAM file after computing metrics.
+  if ! rm -f "$sorted"; then
+    echo "ERROR: Cannot delete '$sorted'"
+  fi
 
   echo -e "$(DATE)\tDONE\t$bam"
 }
@@ -169,14 +174,16 @@ configure_run() {
   #     2. The config in the current directory.
   #     3. The config in the home directory.
   if [[ -f "$PICARDMETRICS_CONFIG" ]]; then
-    source "$PICARDMETRICS_CONFIG"
-  elif [[ -f .picardmetricsrc ]]; then
-    source .picardmetricsrc
-  elif [[ -f ~/.picardmetricsrc ]]; then
-    source ~/.picardmetricsrc
+    continue
+  elif [[ -f picardmetrics.conf ]]; then
+    PICARDMETRICS_CONFIG=picardmetric.conf
+  elif [[ -f ~/picardmetrics.conf ]]; then
+    PICARDMETRICS_CONFIG=~/picardmetrics.conf
   else
     echo "WARNING: Config file '$PICARDMETRICS_CONFIG' not found" >&2
   fi
+  echo -e "$(DATE)\tLoading '$PICARDMETRICS_CONFIG'" >&2
+  source "$PICARDMETRICS_CONFIG"
 
   # All jobs will be launched with niceness=20 by default.
   if [[ -z "$NICENESS" ]]; then
